on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * 0'

name: analyse
jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      #actions: read
      #contents: read

    steps:
      - name: 'Setup Environment'
        shell: bash
        run: |
          git config --global core.autocrlf false
      - name: 'Install Go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: 1.19
        #  go-version-file: go.mod
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
      - name: 'Test'
        run: |
          make build

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
          # languages: go, javascript, csharp, python, cpp, java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2